services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    image: py-fastapi-sqlite
    container_name: python-pip-server
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    volumes:
      - .:/app